### ISSUE TITLE
Failed to run launch checking not working with Learn Rust Introduction / Getting started / Hello World

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#248]
Failed to Launch Check is not working 
There is no message under the build tool window

**Comment by cameronsstone** [comment]
Same here. Same for New Variable Binding task. The Check button *does* work for the Introduce Variable task, it's not all Check button presses that fail.

I get a nice stack trace in the logs from the Check button press:
```
2023-05-10 22:37:44,553 [  47715] SEVERE - #c.i.o.p.Task - Found class org.rust.cargo.project.settings.RustProjectSettingsService, but interface was expected
java.lang.IncompatibleClassChangeError: Found class org.rust.cargo.project.settings.RustProjectSettingsService, but interface was expected
	at com.jetbrains.edu.rust.checker.RsEnvironmentChecker.getEnvironmentError(RsEnvironmentChecker.kt:15)
	at com.jetbrains.edu.learning.checker.EduTaskCheckerBase.check(EduTaskCheckerBase.kt:44)
	at com.jetbrains.edu.learning.actions.CheckAction$StudyCheckTask.localCheck(CheckAction.kt:169)
	at com.jetbrains.edu.learning.actions.CheckAction$StudyCheckTask.run(CheckAction.kt:149)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-10 22:37:44,555 [  47717] SEVERE - #c.i.o.p.Task - IntelliJ IDEA 2023.1.1  Build #IU-231.8770.65
2023-05-10 22:37:44,555 [  47717] SEVERE - #c.i.o.p.Task - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-05-10 22:37:44,555 [  47717] SEVERE - #c.i.o.p.Task - OS: Mac OS X
2023-05-10 22:37:44,556 [  47718] SEVERE - #c.i.o.p.Task - Plugin to blame: JetBrains Academy version: 2023.4-2023.1-464
```

**Comment by igalimov** [comment]
Hi! Thank you for reporting this! The issue is currently under investigation. You can track the progress in our tracker on YouTrack: https://youtrack.jetbrains.com/issue/EDU-5918/Failed-to-launch-checking-in-Learn-Rust-course-in-CLion. 
I'll update this thread with any new information.

**Comment by kochaika** [comment]
Fixed
